# Generated by Django 5.1.7 on 2025-03-26 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamerraterapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamereview',
            name='rating',
        ),
        migrations.DeleteModel(
            name='GameRating',
        ),
    ]
