# Generated by Django 5.1.7 on 2025-03-26 15:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamerraterapi', '0002_remove_gamereview_rating_delete_gamerating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gamereview',
            unique_together={('user', 'game', 'content')},
        ),
    ]
